# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dcd9728525f08c2e6f32d1b93a37d82448b428b514c4832e1eae8821edfb947b11ca3777b2946ec4b3ddc3a5c5837d0ae74d478673d7f481001fdd7bcc68a1e5

test:
  secret_key_base: 37bb753f84f61d71e81000b07aede0394e7c1e4c7ae9f178f724a1858d01e596c0799473447048da0ce38fcae737c01ea4f967a551d3768c5b3c0f31652530fd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
